apiVersion: v1
kind: Deployment
metadata:
  name: meureplicaset
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversao
    template:
      metadata:
        labels:
           app: conversao
      spec: 
        containers: 
        -  name: site
          image: nizzola/api-conversao
          ports:
            - containerPort: 80